- id: wsc
  name: "Winterhawks Ice Center (Beaverton)"
  icsUrl: "https://beaverton-stick-and-puck.darkknightshockey.com"
  siteUrl: "https://winterhawksskatingcenter.com/registration"
  color: "#0072B2"
  enabled: true

- id: sherwood
  name: "Sherwood Ice Arena"
  icsUrl: "https://sherwood-stick-and-puck.darkknightshockey.com"
  siteUrl: "https://www.winterhawksice.com/sherwood-schedule"
  color: "#CC79A7"
  enabled: true

- id: mv
  name: "Mountain View Ice Arena"
  icsUrl: "https://mountainview-stick-and-puck.darkknightshockey.com"
  siteUrl: "https://15560.ezfacility.com/Sessions?reset=True"
  color: "#E69F00"
  enabled: true

- id: vmc
  name: "Veterans Memorial Coliseum"
  icsUrl: "https://vmc-clinics.darkknightshockey.com"
  siteUrl: "https://wicadulthockey.sportngin.com/page/show/3326613--center-evaluations-and-adult-youth-hockey-skills-class-center-"
  color: "#009E73"
  enabled: true